# Generated by Django 5.0.3 on 2024-03-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutriModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('caloria', models.CharField(max_length=30, verbose_name='caloria')),
                ('proteina', models.CharField(max_length=30, verbose_name='proteina')),
                ('carboidrato', models.CharField(max_length=30, verbose_name='carboidrato')),
                ('acuca', models.CharField(max_length=30, verbose_name='acauca')),
            ],
        ),
    ]
