# Generated by Django 5.0.3 on 2024-03-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrimodel',
            name='acuca',
            field=models.CharField(max_length=30, verbose_name='acuca'),
        ),
    ]
