# Generated by Django 5.0.3 on 2024-03-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcad', '0002_alter_nutrimodel_acuca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrimodel',
            name='acuca',
            field=models.CharField(blank=True, max_length=30, verbose_name='acuca'),
        ),
        migrations.AlterField(
            model_name='nutrimodel',
            name='caloria',
            field=models.CharField(blank=True, max_length=30, verbose_name='caloria'),
        ),
        migrations.AlterField(
            model_name='nutrimodel',
            name='carboidrato',
            field=models.CharField(blank=True, max_length=30, verbose_name='carboidrato'),
        ),
        migrations.AlterField(
            model_name='nutrimodel',
            name='proteina',
            field=models.CharField(blank=True, max_length=30, verbose_name='proteina'),
        ),
    ]
