# Generated by Django 5.0.3 on 2024-03-08 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcad', '0003_alter_nutrimodel_acuca_alter_nutrimodel_caloria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrimodel',
            name='caloria',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='caloria'),
        ),
        migrations.CreateModel(
            name='RefeicaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('J', 'Jantar'), ('C', 'café'), ('N', 'Nenhuma das opções')], max_length=1, verbose_name='tipo')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcad.nutrimodel')),
            ],
        ),
    ]
