# Generated by Django 5.0.3 on 2024-03-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcad', '0004_alter_nutrimodel_caloria_refeicaomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefeicaoModel',
        ),
    ]
